### ISSUE TITLE
Setup your Social Media

### ISSUE THREAD

**Issue by roughani** [code4sac/codeacross-2016#10]
### Setup your Social Media

Set up your social media hashtag at least a few weeks prior to your event and make the hashtag known on your registration page. 
- For CodeAcross, we use the #codeacross hashtag
- For National Day of Civic Hacking we use #hackforchange. 
- If you have your own hashtag that you use for your regular Brigade Meetups, use that too. 

Tweeting and posting throughout the day will help encourage other people in the community as well as help set up a timeline of events. This will make it easier to blog about your event later.
- [x] Designate someone to craft promotional tweets leading up to the event 
- [ ] Designate someone to live tweet throughout the event using the relevant hashtags (assign this person to #18)

**Comment by joelrip** [comment]
Talk to Hacker Lab about marketing

**Comment by dpugh143** [comment]
I will start tweeting about CodeAcross also

**Comment by dpugh143** [comment]
Do we already have hashtags for the event, or do we need to think of some: #codeacross, #civictech, #sacramento... Any suggestions?

**Comment by joelrip** [comment]
#CodeAcross is the official from CfA, and #hack4sac is the County Challenge
one. Do we need more?

**Comment by roughani** [comment]
I have a bias for #Hack4Sac. It will help the county and I actually renamed the event Sacramento County Civic Hackathon because I thought that CodeAcross would be too confusing of a brand identity after we just rolled out Hack4Sac a few days prior at the March 1 Kickoff Event. I agree that it's best to only have one hashtag.
